# netlify.toml

[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions/"

[build.environment]
  PYTHON_VERSION = "3.11"

# This rule now forwards ALL requests to your FastAPI app.
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200